version: '3.1'

services:

  mysql:
    image: 'mysql:8.0'
    environment:
      - MYSQL_ROOT_PASSWORD=teste
      - MYSQL_PASSWORD=teste
      - MYSQL_USER=teste
      - MYSQL_DATABASE=teste

    ports:
      - '3306:3306'